version: '3.8'

services:

  web_general:
    build: ./services/web
    environment:
      FLASK_APP: web.py
      APP_FOLDER: /home/app/web
      COUNTRY: General Server
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000

  web_uk:
    build: ./services/web
    environment:
      FLASK_APP: web.py
      APP_FOLDER: /home/app/web
      COUNTRY: UK Server
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000

  web_us1:
    build: ./services/web
    environment:
      FLASK_APP: web.py
      APP_FOLDER: /home/app/web
      COUNTRY: US Server 1
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000

  web_us2:
    build: ./services/web
    environment:
      FLASK_APP: web.py
      APP_FOLDER: /home/app/web
      COUNTRY: US Server 2
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000

  web_backup:
    build: ./services/web
    environment:
      FLASK_APP: web.py
      APP_FOLDER: /home/app/web
      COUNTRY: Backup Server 
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000

  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    volumes:
      - ./services/nginx/config/proxy.conf:/etc/nginx/conf.d/default.conf
      - ./services/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/config/upstream.conf:/etc/nginx/conf.d/00-upstream.conf

    depends_on:
      - web_backup
      - web_general
      - web_uk
      - web_us1
      - web_us2

